apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: 2017-11-21T22:42:10Z
  labels:
    app: msp-1.3-prototype
  name: msp-1.3-prototype-build
  namespace: gcpe-mygovbc-msp-demo
  resourceVersion: "335613542"
  selfLink: /oapi/v1/namespaces/gcpe-mygovbc-msp-demo/buildconfigs/msp-1.3-prototype-build
  uid: 35fd7fb9-cf0d-11e7-837a-0050568379a2
spec:
  completionDeadlineSeconds: 1800
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: msp-1.3-prototype:latest
  postCommit: {}
  resources:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 2Gi
  runPolicy: Parallel
  source:
    dockerfile: |-
      FROM msp-1.3-prototype-build-angular-app:latest
      COPY * /tmp/app/dist/
      CMD  /usr/libexec/s2i/run
    images:
    - from:
        kind: ImageStreamTag
        name: msp-1.3-prototype-build-angular-app:latest
      paths:
      - destinationDir: tmp
        sourcePath: /opt/app-root/src/dist/.
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: nginx-runtime-1.3-prototype:latest
    type: Docker
  triggers:
  - imageChange:
      lastTriggeredImageID: 172.50.0.2:5000/gcpe-mygovbc-msp-demo/nginx-runtime-1.3-prototype@sha256:c917c5374dc8cff6a1bb94ab7ee949f4e15aabb2f007cda07a7d08496a56849f
    type: ImageChange
status:
  lastVersion: 20
