apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: 2017-11-21T22:51:32Z
  generation: 29
  labels:
    app: msp-1-3-prototype
  name: msp-1-3-prototype
  namespace: gcpe-mygovbc-msp-demo
  selfLink: /oapi/v1/namespaces/gcpe-mygovbc-msp-demo/deploymentconfigs/msp-1-3-prototype
  uid: 8522ffcd-cf0e-11e7-837a-0050568379b2
spec:
  replicas: 2
  selector:
    app: msp-1-3-prototype
    deploymentconfig: msp-1-3-prototype
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: msp-1-3-prototype
        deploymentconfig: msp-1-3-prototype
    spec:
      containers:
      - env:
        - name: RealIpFrom
          value: 172.51.0.0/16
        - name: AdditionalRealIpFromRules
          value: set_real_ip_from 142.34.208.209; set_real_ip_from 142.34.63.248/29;
        - name: IpFilterRules
          value: allow 0.0.0.0/0; deny all;
        - name: HTTP_BASIC
        - name: HTTP_BASIC_USERNAME
          value: ${HTTP_BASIC_USERNAME}
        - name: HTTP_BASIC_PASSWORD
          value: ${HTTP_BASIC_PASSWORD}
        image: 172.50.0.2:5000/gcpe-mygovbc-msp-demo/msp-1.3-prototype@sha256:fc48a7e693df58b9208dd7a57bcc04a1fd04c68ca54fff7e864967bc0029136e
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /nginx_status
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 60
        name: msp-1-3-prototype
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /nginx_status
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 60
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - msp-1-3-prototype
      from:
        kind: ImageStreamTag
        name: msp-1.3-prototype:demo
        namespace: gcpe-mygovbc-msp-demo
      lastTriggeredImage: 172.50.0.2:5000/gcpe-mygovbc-msp-demo/msp-1.3-prototype@sha256:fc48a7e693df58b9208dd7a57bcc04a1fd04c68ca54fff7e864967bc0029136e
    type: ImageChange
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: 2018-02-08T03:13:44Z
    lastUpdateTime: 2018-02-08T03:13:44Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: 2018-02-08T04:37:58Z
    lastUpdateTime: 2018-02-08T04:37:59Z
    message: replication controller "msp-1-3-prototype-15" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - imageTrigger:
        from:
          kind: ImageStreamTag
          name: msp-1.3-prototype:demo
          namespace: gcpe-mygovbc-msp-demo
      type: ImageChange
    message: image change
  latestVersion: 15
  observedGeneration: 29
  readyReplicas: 2
  replicas: 2
  unavailableReplicas: 0
  updatedReplicas: 2
